# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/crazy/market/models/category/fields.yaml

# Model Class name
modelClass: Crazy\Market\Models\Category

# Default redirect location
defaultRedirect: crazy/market/categories

# Create page
create:
    title: backend::lang.form.create_title
    redirect: crazy/market/categories/update/:id
    redirectClose: crazy/market/categories

# Update page
update:
    title: backend::lang.form.update_title
    redirect: crazy/market/categories
    redirectClose: crazy/market/categories

# Preview page
preview:
    title: backend::lang.form.preview_title
